# DataSource Configuration (PostgreSQL from environment variables)
spring.datasource.url=jdbc:postgresql://${HOST_DB:localhost}:${PORT_DB:5432}/${POSTGRES_DB:bookingya}
spring.datasource.driverClassName=org.postgresql.Driver
spring.datasource.username=${USERNAME_DB:postgres}
spring.datasource.password=${PASSWORD_DB:postgres}

# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

# Server Port
server.port=8080
server.servlet.context-path=/api

# Logging
logging.level.root=WARN
logging.level.com.project.bookingya=INFO

